AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the webservices Slack app
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - production
  SlackToken:
    Description: Slack OAuth Token
    Type: String
  SlackChannel:
    Description: Slack channel that the action will happen in, e.g. 'quiz'
    Type: String
Globals:
  Function:
    Timeout: 12
Resources:
  QuizScraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: 'quizScraper.handler'
      CodeUri: features/quizScraper/
      Environment:
        Variables:
          "SLACK_TOKEN": !Ref SlackToken
          "SLACK_CHANNEL": !Ref SlackChannel
      Description: 'This Lambda function will scrape the Stuff Quiz page for the most recent quiz'
      Runtime: nodejs12.x
      Events:
        QuizEventQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ScrapeQuizQueue.Arn
  QuizResults:
    Type: AWS::Serverless::SimpleTable
  ScrapeQuizQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy: 
          deadLetterTargetArn: !GetAtt FailedQuizScrapeQueue.Arn
          maxReceiveCount: 5
  FailedQuizScrapeQueue:
    Type: AWS::SQS::Queue
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: 'Cloudwatch event that invokes the lambda script that posts to slack'
      # ScheduleExpression: cron(2 3,19 * * ? *)
      ScheduleExpression: rate(2 minutes)
      Targets:
        - Arn: !GetAtt ScrapeQuizQueue.Arn
          Id: 'TargetFunctionV1'