version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            # - run: npm install
            # - run: npm run deploy
            - run: echo "Success"
workflows:
    build-and-test:
      jobs:
        - build-and-test
    deploy:
      jobs:
        - build-and-test
        - build-and-deploy
          requires:
            - build-and-test
          filters:
            branches:
              only: release