version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            # - run: npm install
            # - run: npm run deploy
            - run: echo "Success"
workflows:
    build-test-deploy:
      jobs:
        - test
        - deploy:
              filters:
                branches:
                  only: master